# Generated by Django 3.0.5 on 2021-03-30 11:22

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookid', models.IntegerField(db_column='_id', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=200)),
                ('pagecount', models.IntegerField(db_column='pageCount')),
                ('publisheddate', models.CharField(blank=True, db_column='publishedDate', max_length=200, null=True)),
                ('categories', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('memberid', models.IntegerField(db_column='memberID', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'db_table': 'fine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentno', models.AutoField(db_column='paymentNo', primary_key=True, serialize=False)),
                ('paymentmethod', django_mysql.models.EnumField(blank=True, choices=[('DEBIT CARD', 'Debit Card'), ('CREDIT CARD', 'Credit Card')], db_column='paymentMethod', default=None, null=True)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reserverid', models.IntegerField(db_column='reserverID', primary_key=True, serialize=False)),
                ('bookid', models.IntegerField(db_column='BookID')),
            ],
            options={
                'db_table': 'reservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('bookid', models.IntegerField(db_column='_id', primary_key=True, serialize=False)),
                ('availabilitystatus', models.BooleanField(db_column='availabilityStatus', default=True)),
                ('expectedduedate', models.DateField(blank=True, db_column='expectedDueDate', default=None, null=True)),
                ('borrowerid', models.ForeignKey(blank=True, db_column='BorrowerID', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.Memberuser')),
            ],
            options={
                'db_table': 'loan',
            },
        ),
    ]
